name: integration-test

on: push

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Launch integration tests
        run: npm run integration-test
